#define SEMICOLON_TOK ';'
#define COMMA_TOK ','
#define LCRLY_TOK '{'
#define RCRLY_TOK '}'
#define LPAREN_TOK '('
#define RPAREN_TOK ')'
#define INT_TOK 1
#define MAIN_TOK 2
#define ID_TOK 3
#define REL_OP_TOK 4
#define ARITH_OP_TOK 5
#define LOGICAL_OP 6
#define BITWISE_OP 7
#define ASSIGN_OP 8
#define FLOAT_TOK 9
#define CHAR_TOK 10
#define FOR_TOK 11
#define DO_TOK 12
#define WHILE_TOK 13
#define IF_TOK 14
#define ELSE_TOK 15
#define HEADER_TOK 16
#define INTCONST_TOK 17
